# Generated by Django 4.2.5 on 2023-10-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
    ]
